### ISSUE TITLE
Request a prop for onImageLoad so apps know when images are loaded

### ISSUE THREAD

**Issue by animepauly** [fritz-c/react-image-lightbox#103]
I would like to request a prop for onImageLoad, so I know when an image has been loaded. I noticed you have an error prop, so I would just like if this was updated to include a success load handler as well.

My use case is that I am using this great component to just load one image at a time. I have a timer for players to view the image and when that timer finishes, the lightbox closes. This all works great when I'm on a fast internet connection, but when then connection is slower, several seconds go by before the image loads all the while my timer is running. I would like to start the timer when the image loads and I do not know when that is with this current version. Thanks!

**Comment by fritz-c** [comment]
Added as of v4.6.0
