### ISSUE TITLE
Close button styles are overridden by Twitter Bootstrap

### ISSUE THREAD

**Issue by kzviagina** [fritz-c/react-image-lightbox#15]
Hello!

Thanks a lot for this component!
We use it in our React project with Twitter Bootstrap and webpack. Unfortunately we found that, ``.close`` css class styles are overridden by Twitter Bootstrap. Is it possible to replace them by something more specific (like ``ril-close`` or ``react-image-lightbox-close``), to keep ability to customize component and not to be overridden accidentally?

**Comment by fritz-c** [comment]
Sorry, this was a big oversight on my part. I've added the `ril-` prefixed classes as you suggested, but I'm afraid I have to leave the classes until the next major release, as removing them would be a breaking change. In the meantime, you may have to write some CSS that protects the lightbox style from being overridden by bootstrap.

**Comment by kzviagina** [comment]
Thanks a lot for a quick feedback and for this update!
