### ISSUE TITLE
Loader/Spinner for load big images

### ISSUE THREAD

**Issue by jcyusupov** [fritz-c/react-image-lightbox#18]
Hi! Thank you very much for this library! I really like it. Could you please add loader/spinner for loading big images? Thank you!

**Comment by fritz-c** [comment]
Thanks for using it! As for the spinner, I just added it in [3.0.3](https://github.com/fritz-c/react-image-lightbox/releases/tag/v3.0.3). Could you check if that works for you?

**Comment by c00kiemon5ter** [comment]
The spinner is working fine 👍 
I think this can be closed.

**Comment by jcyusupov** [comment]
Yep, the spinner is working fine! Thank you!
