### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by th3fallen** [fritz-c/react-image-lightbox#21]
Do you happen to know what browsers this is compatible with?

**Comment by fritz-c** [comment]
Image navigation works in at least IE 9 and above. IE 9 doesn't support 3D CSS transforms, though, so the zoom in/out does not work. I haven't tested below IE 9. Here's the breakdown of what I know:
Firefox (latest): all functionality ok
Chrome (latest): all functionality ok
Safari (latest): all functionality ok
IE 11: all functionality ok
IE 10: ??
IE 9: Image display and navigation ok. Transitions and zoom do not work.

**Comment by th3fallen** [comment]
Awesome, thanks man

**Comment by fritz-c** [comment]
I need to at least add this to the README, so I'm reopening this for now. I just realized that the zoom issues may have been due to a lack of prefixes. I'll update the readme once all is fixed and I can push the update.

**Comment by fritz-c** [comment]
I've fixed the issues in IE 9, so the zoom feature can be used now.
I also added the compatibility chart to make it obvious what platforms are supported.
Thanks for bringing this up!
