### ISSUE TITLE
Ability to change close button class?

### ISSUE THREAD

**Issue by th3fallen** [fritz-c/react-image-lightbox#22]
Wondering if you have a way to change the close button class as bootstrap interferes with it and screws it appearance up.

**Comment by fritz-c** [comment]
This is set to be fixed in version 4 (see #16) as it's a breaking change. In the meantime, you could add some styles to the ril-close class to override the bootstrap stuff.

**Comment by th3fallen** [comment]
Sounds good just wanted ask before i spent the time overwriting styles. thanks for being so quick man.

**Comment by fritz-c** [comment]
Yeah, no problem. Sorry for the inconvenience.
