### ISSUE TITLE
Toolbar Item Child height via css

### ISSUE THREAD

**Issue by itsjimbo** [fritz-c/react-image-lightbox#23]
I realize you can set the toobar height through css with something like 
```
.ril-toolbar{
    height: 200px!important;
}
```
But toolbarItemChild is only set from scss, is there a way to change the item child line-height?

**Comment by fritz-c** [comment]
Sorry for the delay, this is available now in [release v3.1.0](https://github.com/fritz-c/react-image-lightbox/releases/tag/v3.1.0) via the `.ril-toolbar__item` class
