### ISSUE TITLE
Fix zoom out behavior

### ISSUE THREAD

**Issue by fritz-c** [fritz-c/react-image-lightbox#25]
When zooming in on one point in an image and then zooming out from another, the image can start to slide outside of the viewport. I've tried to reduce the effects with max offset settings, but the result (and current implementation) is jerky and not at all eye-pleasing.

![zoomout](https://cloud.githubusercontent.com/assets/4413963/17832869/1890bb6c-6749-11e6-9e4d-471c4a26e739.gif)

I'm certain that the right computations will provide both smooth zooming in and out from any point on the image, but after a couple hours trying out different things, I'm still at a loss. If anyone could offer some advice on how to handle this, I would be very grateful. The relevant code can be found here: https://github.com/fritz-c/react-image-lightbox/blob/master/src/react-image-lightbox.js#L212-L246

**Comment by tiemevanveen** [comment]
Hey, thanks for the lightbox, works great. 

Sorry if this is not helping.. but I noticed that while doing this (zoom in and out on a different spot) the images sometimes disappears completely and sometimes when closing the lightbox the body is still locked. Not sure if this is related to this issue though..

**Comment by fritz-c** [comment]
This fix is now available in `v3.3.1`
