### ISSUE TITLE
Non browser env incompatible

### ISSUE THREAD

**Issue by xuopled** [fritz-c/react-image-lightbox#34]
`react-image-lightbox` is incompatible with non browser env.

It cannot be used in a module bundler like Webpack that uses `use strict`.

When I include the script in my project with `import Lightbox from "react-image-lightbox"`

and I try to build my project (it execute the javascript in a non browser env) I have this error: `window is not defined`

You use the `window` variable in `src/util.js` and `src/react-image-lightbox.js`.

I think the problem could be resolve surrounding all `window`uses by

```
if(typeof window != 'undefined'){
```

So I did and after I had the same problem with `document` var. 

For more explanations, please read this article, in particular the section `Wait, you tried to run my code where?`
https://nolanlawson.com/2015/10/19/the-struggles-of-publishing-a-javascript-library/

**Comment by bkniffler** [comment]
Shame, I really like this lightbox, but having window and document all over the place is a total showstopper.

**Comment by tiemevanveen** [comment]
See: https://github.com/fritz-c/react-image-lightbox/issues/27

**Comment by psrebniak** [comment]
@xuopled I think this can be marked as solved - currently code is running fine with non browser env.

**Comment by xuopled** [comment]
great, thank you
