### ISSUE TITLE
react-bootstrap 3 navbar fixedTop

### ISSUE THREAD

**Issue by sandervanhooft** [fritz-c/react-image-lightbox#42]
Hi @fritz-c ,

When using this lightbox with [react-bootstrap 3's  navbar](https://react-bootstrap.github.io/components.html#navbars) with fixedTop (a.k.a. sticky), the navbar keeps visible, on top of the lightbox.

Do you perhaps have a suggestion to fix this?

Kind regards,

Sander

**Comment by fritz-c** [comment]
Check out the prop `reactModalStyle` and its description in the README. You should be able to fiddle with the z-index of the modal to make it come out on top.

**Comment by sandervanhooft** [comment]
@fritz-c Thanks, that worked like a charm!

For future reference:  `z-index` CSS is `zIndex` in React.
