### ISSUE TITLE
React 15.5.0 support

### ISSUE THREAD

**Issue by zslabs** [fritz-c/react-image-lightbox#51]
Hi! Was wondering if [React 15.5.0](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) support was on your radar. Not that it's technically broken, but because of the separation of the `PropTypes` separation, using your package in newer projects shows a lot of warnings. Happy to work on a PR for this, but wasn't sure what else was tied up that may be targeting older versions.

**Comment by fritz-c** [comment]
Thanks for bringing my attention to this! Fixed now in v3.4.3
