### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by szyablitsky** [fritz-c/react-image-lightbox#6]
Hi Chris! Great work overall!
It would be nice if you add mobile browsers support (touch).
Right now component does not move zoomed image but scrolls the page underneath.

**Comment by szyablitsky** [comment]
Thank you!

**Comment by fritz-c** [comment]
@szyablitsky FYI, mobile browser support is now even better in `v3.4.0`, thanks to #39

**Comment by szyablitsky** [comment]
@fritz-c great news! Thank you!
