### ISSUE TITLE
Images blurry in iOS Safari

### ISSUE THREAD

**Issue by sbking** [fritz-c/react-image-lightbox#69]
On iOS Safari, the images are extremely blurry. You can see this on the demo page on an iPhone with iOS 10.3. I believe this is happening because of how the images are scaled.

Right now, the image is given a width/height to fit in the browser viewport, and then a transform is used to scale the image based on that. This means that on iOS Safari, a 2000x2000 image might be rendered initially at, say, 750x750. When it is transformed, iOS Safari seems to keep the initially rendered snapshot and transform that, so you get a blurry version of the image when zoomed in.

To fix this, I think it could be possible to change the logic so that it initially displays the image at the full image resolution, and then applies a transform to that to adjust it to the viewport size, and continue to use the full image resolution as the basis for calculating the transforms.

**Comment by fritz-c** [comment]
Confirmed this. The fix you suggested sounds like the ideal one. Would you be interested in submitting a pull request?
