### ISSUE TITLE
Orange border on mobile view

### ISSUE THREAD

**Issue by bruce-webber** [fritz-c/react-image-lightbox#72]
When I view the demo using my Samsung S7, I see an orange border around the image. Is there a way disable this, perhaps by passing a style directive to React Modal?

See the attached screenshot from my phone. It's difficult to see in this image, but you can see orange lines on the left and right side of the photo.

![react-image-lightbox-samsung7](https://user-images.githubusercontent.com/300414/31227947-aaedf472-a9a9-11e7-86be-1b9075a6283a.png)

**Comment by sbking** [comment]
@bruce-webber This should be fixed by #77. Until then, you can do this:

```css
    .viewer-wrapper {
      outline: none;
    }
```

```js
    <Lightbox
      {...otherProps}
      wrapperClassName='viewer-wrapper'
    />
```
