### ISSUE TITLE
Update `react-modal`

### ISSUE THREAD

**Issue by zslabs** [fritz-c/react-image-lightbox#75]
Hi @fritz-c,
In doing some testing to see if I can upgrade an app to React 16, it looks like this library is using `react-modal` which is using an unsupported API to interact with portals in newer version of React. It looks like there's an update available that may solve the issue and wanted to know if this was something on your plate already or if you needed some assistance. Thanks!

**Comment by zslabs** [comment]
Went ahead and created a PR to resolve this. All appears to be working alright on my end.

**Comment by fritz-c** [comment]
Thank you for the PR. When I checked this out a week or so ago, react-modal@3 had yet to be released. Thanks for picking up the slack.
