### ISSUE TITLE
Tab Focus moves in the background

### ISSUE THREAD

**Issue by zee0786** [fritz-c/react-image-lightbox#79]
Tab Focus moves out of the lightbox after the close icon instead of rotating within the lightbox. I have fixed this code on my local machine but unable to push my branch due to authorization. Please help me

**Comment by fritz-c** [comment]
If you fork the repository and push your changes to a branch there, you can submit a pull request. I’m curious to see how you fixed this.

**Comment by zee0786** [comment]
Thanks. I have raised a pull request. Kindly review it

**Comment by fritz-c** [comment]
Actually, this seems to be a react-modal issue. They have a WIP pull request here: 
https://github.com/reactjs/react-modal/pull/521
I will wait on that for the fix. Thank you for the time you put into submitting your pull request for this library's sake.

**Comment by diasbruno** [comment]
Hi @zee0786 @fritz-c, it seems that we need to improve the tabbing mechanism on `react-modal`. Hopefully I'll try to finish this PR today.

**Comment by zee0786** [comment]
No Problem @diasbruno , I am using forked repo of the same

**Comment by fritz-c** [comment]
It's been fixed in react-modal now.
