### ISSUE TITLE
Broken images can overlay spinner

### ISSUE THREAD

**Issue by zslabs** [fritz-c/react-image-lightbox#82]
Right now if there is an invalid image in the lightbox, the spinner can overlap the other images; depending on where it falls in the ordering. Right now there is a `onImageLoadError` prop that can be used, but it currently doesn't have a default as far as how to handle the UI. In the gif below I added in a small snippet to take care of not degrading the other images, but ideally we would not even show the loader and instead have some error text that could be shown/customized.

![lightbox](https://user-images.githubusercontent.com/1018402/31834723-f54d3902-b59c-11e7-834f-110b4730ff59.gif)

**Comment by wuweiweiwu** [comment]
@fritz-c Can I take this?

**Comment by fritz-c** [comment]
@wuweiweiwu Sure!

**Comment by fritz-c** [comment]
Fixed now in `v4.5.0`, thanks to @wuweiweiwu!
