### ISSUE TITLE
[Question] preferred way of styling the component or setting custom zIndex

### ISSUE THREAD

**Issue by thomasmery** [fritz-c/react-image-lightbox#9]
Hi,

thanks for this component,

just started using it and although base styles work just fine I need to change the `z-index` of the lightbox for it to be placed above another box that I can't change the z-index of (also might have to tweak other styles as well to match some other styles in my app)

so I was wondering if there was a preferred way of modifying the styles, apart from overriding with `important` in my own style sheets

thanks for your time

**Comment by fritz-c** [comment]
Actually there is not a way to modify the styles at this time. The package uses radium for styling, which is pretty easy to mix custom styles into, so if you're not averse to making a pull request allowing for custom styles injected via props, I can guarantee I'll look at it asap.

For starters, if you wanted to change the z-axis of the modal element (though I'm considering eventually changing this part to the `react-modal` component), you could add a style attribute to the `<modal>` tag here: https://github.com/fritz-c/react-image-lightbox/blob/master/src/ReactImageLightbox.js#L950

**Comment by thomasmery** [comment]
Thanks,

I'd really like being able to contribute, I'll try if time allows in the next few weeks

anything I should know about building? I'm not so good with npm and build tools

I see you have a `release` script 

how would I run it?

just running `gulp` in the `node_modules/react-image-lightbox` directory?

thanks

**Comment by fritz-c** [comment]
You'll want to fork the repository, and then clone it to a directory on your computer via 
```
git clone git@github.com:thomasmery/react-image-lightbox.git
```
and work inside that. You push commits to one of your branches, and create a pull request for that branch from github.

I used the gulp tasks from https://github.com/JedWatson/react-component-gulp-tasks
So everything will be the same as in there, but I think the only command you'll need to know is `gulp dev` (also mapped to `npm start`), which starts up a local dev server, and you can see the effects of your changes on the sample page served up. All the build and publishing stuff I'll handle after merging a pull request.

**Comment by fritz-c** [comment]
@thomasmery Were you able to get it working for you?

**Comment by thomasmery** [comment]
Hi,

sadly I had no time to work on a proper solution and ended up modifying the zIndex in my css.

sorry I did not warn you

**Comment by fritz-c** [comment]
No, that's perfectly fine. Sorry for not making it customizable enough. I'll let you know when I make a release that better enables user styles.

**Comment by fritz-c** [comment]
As of  [release v3.1.0](https://github.com/fritz-c/react-image-lightbox/releases/tag/v3.1.0), the `reactModalStyle` prop can be used to customize the z-index, etc., of the modal holding the lightbox. Thanks for making this suggestion.
