### ISSUE TITLE
Warning: react-modal: App element is not defined.

### ISSUE THREAD

**Issue by arpitprod** [fritz-c/react-image-lightbox#94]
Showing this warning after update reactjs 

`Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen reades don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.`

check same in react-modal for how to remove this warning
[https://github.com/reactjs/react-modal/issues/576](url)

How to solve same here ?

**Comment by HaraKeisuke** [comment]
I have same issue.

**Comment by nicubarbaros** [comment]
Same issue.

**Comment by fritz-c** [comment]
I had this same issue in another project using react-modal, and will be fixing it when I get some time to. Should be in the next few days.

**Comment by mentrie** [comment]
I'm having same warning and after closing the lightbox images, the page stops scrolling

**Comment by fritz-c** [comment]
Should be fixed now as of `v4.4.0`
